### ISSUE TITLE
Previous work removed

### ISSUE THREAD

**Issue by bockensm** [commandbox-modules/commandbox-codechecker#11]
In #10 I added support for excluded paths and it was accepted here: https://github.com/commandbox-modules/commandbox-codechecker/commit/0e08696df4bfa9b921c55d34994a8276f2b32ea6

In https://github.com/commandbox-modules/commandbox-codechecker/commit/18a9f8d57ee758cc9fd0e3a0ec4ee8e986ed8e33 that work was (likely) unintentionally overwritten, removing support for the `excludePaths` CLI arg.

If it was removed intentionally, can I know what the reason is so I can submit a new PR?

**Comment by bdw429s** [comment]
Whoops, that's odd.  I must have missed pulling some changes locally before that commit.  I know I didn't intentionally remove any of the exclude paths stuff, so I must have just been on an older version of the repo or something.  There is stuff in that commit I did remove on purpose, but the exclude paths wasn't part of it.  Yes, please send that back again and I'll merge it.

**Comment by bdw429s** [comment]
@bockensm Ok, this logic should be back in place now.  Please confirm and sorry again for accidentally removing it!
